---
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
            # each hook takes about 1s to run. These are expensive-ish checks
            -   id: check-added-large-files
            -   id: check-yaml
            -   id: check-builtin-literals
            -   id: check-byte-order-marker
            -   id: check-case-conflict
            -   id: check-merge-conflict
            -   id: check-symlinks
            -   id: check-toml
            -   id: debug-statements
            -   id: detect-private-key
            -   id: fix-encoding-pragma
                args: [ --remove ]
            -   id: forbid-new-submodules
    -   repo: https://github.com/abravalheri/validate-pyproject
        rev: v0.17
        hooks:
            -   id: validate-pyproject
    -   repo: https://github.com/psf/black
        rev: 24.4.2
        hooks:
            -   id: black
    -   repo: https://github.com/charliermarsh/ruff-pre-commit
        rev: v0.4.3
        hooks:
            -   id: ruff
                exclude: ^markdown_to_json/vendor/.*$
                args: [
                    "--config",
                    "pyproject.toml",
                ]
